repos:
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: e805244dd1bc999f2b4d716f5fa21ee87189b084 # 0.12.2
  hooks:
    - id: uv-lock
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: 39d9ac5938dadb73df0564a45f163e25ff9fa6e2 # v0.16.1
  hooks:
    # Run the linter. https://docs.astral.sh/ruff/linter/
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter. https://docs.astral.sh/ruff/formatter/
    - id: ruff-format