repos:
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0f4b65a503cc866b9b5e62dda2020f7943b01a65 # 0.12.22
  hooks:
    - id: uv-lock
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: f12be1ebaa5351c1fc76472de98db2c3446c8253 # v0.16.10
  hooks:
    # Run the linter. https://docs.astral.sh/ruff/linter/
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter. https://docs.astral.sh/ruff/formatter/
    - id: ruff-format